//! Generated by cot CLI 0.3.1 on 2025-07-28 18:12:43+00:00

#[derive(Debug, Copy, Clone)]
pub(super) struct Migration;
impl ::cot::db::migrations::Migration for Migration {
    const APP_NAME: &'static str = "auth";
    const MIGRATION_NAME: &'static str = "m_0001_initial";
    const DEPENDENCIES: &'static [::cot::db::migrations::MigrationDependency] = &[];
    const OPERATIONS: &'static [::cot::db::migrations::Operation] =
        &[::cot::db::migrations::Operation::create_model()
            .table_name(::cot::db::Identifier::new("auth__user"))
            .fields(&[
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("id"),
                    <cot::db::Auto<i64> as ::cot::db::DatabaseField>::TYPE,
                )
                .auto()
                .primary_key()
                .set_null(<cot::db::Auto<i64> as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("username"),
                    <cot::db::LimitedString<254> as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<cot::db::LimitedString<254> as ::cot::db::DatabaseField>::NULLABLE)
                .unique(),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("name"),
                    <cot::db::LimitedString<254> as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<cot::db::LimitedString<254> as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("password"),
                    <cot::auth::PasswordHash as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<cot::auth::PasswordHash as ::cot::db::DatabaseField>::NULLABLE),
                ::cot::db::migrations::Field::new(
                    ::cot::db::Identifier::new("email"),
                    <cot::common_types::Email as ::cot::db::DatabaseField>::TYPE,
                )
                .set_null(<cot::common_types::Email as ::cot::db::DatabaseField>::NULLABLE),
            ])
            .build()];
}

#[derive(::core::fmt::Debug)]
#[::cot::db::model(model_type = "migration")]
struct _User {
    #[model(primary_key)]
    id: cot::db::Auto<i64>,
    #[model(unique)]
    username: cot::db::LimitedString<254>,
    name: cot::db::LimitedString<254>,
    password: cot::auth::PasswordHash,
    email: cot::common_types::Email,
}
